source 'https://rubygems.org'

gem 'rails', '4.2.7'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'haml', '~> 4.0.6'
gem 'paperclip', '~> 4.2.1'
gem 'simple_form', '~> 3.1.0'
gem 'bootstrap-sass', '~> 3.3.3'
gem 'devise'
gem 'acts_as_votable', '~> 0.10.0'
gem 'kaminari', '~> 0.16.3'
gem 'jquery-turbolinks'

# development exclusive gems
group :development do
  gem 'web-console', '~> 2.0'
end

# test and development gems
group :development, :test do
  gem 'byebug'
  gem 'spring'

  gem 'capybara', '~> 2.4.4'
  gem 'rspec-rails', '~> 3.3.0'
  gem 'factory_girl_rails'
end

# test exclusive gems
group :test do
  gem 'shoulda-matchers'
  gem 'cucumber-rails', require: false
  gem 'database_cleaner'
  gem 'selenium-webdriver'
end

